CREATE OR REPLACE FUNCTION RETURN_TEACHER_TITLE(P_ID_TEACHER IN NUMBER)
RETURN VARCHAR2
IS
    V_TITLE VARCHAR2(255);
BEGIN
    SELECT TI.NOMENCLATURE
    INTO V_TITLE
    FROM TITLES TI
    INNER JOIN TEACHERS TE ON TI.ID = TE.FK_TITLE_UID
    WHERE TE.ID = P_ID_TEACHER;

RETURN V_TITLE;
END;
