CREATE TABLE BOARDS
(
    ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    DATE_SCHEDULED TIMESTAMP NOT NULL,
    FK_CLASS_UID NUMBER NOT NULL,
    FK_LEADER_UID NUMBER NOT NULL,
    FK_PROPOSAL_UID NUMBER NOT NULL
);
CREATE TABLE BOARDS_EVALUATORS
(
    FK_BOARD_UID NUMBER NOT NULL,
    FK_EVALUATOR_UID NUMBER NOT NULL
);
CREATE TABLE CLASSES
(
    ID NUMBER CONSTRAINT PK_CLASS PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FK_TEACHER_UID NUMBER NOT NULL,
    FK_SEMESTER_UID NUMBER NOT NULL
);
CREATE TABLE CLASSES_STUDENTS
(
    FK_STUDENT_UID NUMBER NOT NULL,
    FK_CLASS_UID NUMBER NOT NULL,
    AVERAGE NUMBER
);
CREATE TABLE STUDENTS
(
    ID NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
    CPF VARCHAR2(11) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    REGISTRATION VARCHAR2(20) UNIQUE NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL
);
CREATE TABLE INTEREST_AREAS
(
    ID NUMBER CONSTRAINT PK_INTEREST_AREA PRIMARY KEY,
    NAME VARCHAR2(200) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL
);
CREATE TABLE INTEREST_AREAS_TEACHERS
(
    FK_INTEREST_AREA_UID NUMBER NOT NULL,
    FK_TEACHER_UID NUMBER NOT NULL
);
CREATE TABLE EXAMINATIONS
(
    ID NUMBER CONSTRAINT PK_EXAMINATION PRIMARY KEY,
    PRESENTATION VARCHAR2(255) NOT NULL,
    APPROVED NUMBER(1) NOT NULL,
    TEXT_CONTENT VARCHAR2(255) NOT NULL,
    TEXT_STRUCTURE VARCHAR2(255) NOT NULL,
    LANGUAGE VARCHAR2(255) NOT NULL,
    OBSERVATION VARCHAR2(255),
    RELEVANCE VARCHAR2(255) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    NOTE DOUBLE PRECISION NOT NULL,
    TYPE VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FK_PROPOSAL_UID NUMBER NOT NULL,
    FK_TEACHER_UID NUMBER NOT NULL
);
CREATE TABLE SEMESTERS
(
    ID NUMBER CONSTRAINT PK_SEMESTER PRIMARY KEY,
    NAME VARCHAR2(6) NOT NULL
);
CREATE TABLE TEACHERS
(
    ID NUMBER CONSTRAINT PK_TEACHER PRIMARY KEY,
    CPF VARCHAR2(11) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    REGISTRATION VARCHAR2(20) UNIQUE NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FK_TITLE_UID NUMBER NOT NULL
);
CREATE TABLE PROPOSALS
(
    ID NUMBER CONSTRAINT PK_PROPOSAL PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FK_AUTHOR_UID NUMBER NOT NULL,
    FK_LEADER_UID NUMBER NOT NULL
);
CREATE TABLE SUGGESTIONS
(
    ID NUMBER CONSTRAINT PK_SUGGESTION PRIMARY KEY,
    DESCRIPTION VARCHAR2(255) NOT NULL,
    SEARCH NUMBER(1) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FK_TEACHER_UID NUMBER NOT NULL
);
CREATE TABLE TITLES
(
    ID NUMBER CONSTRAINT PK_TITLE PRIMARY KEY,
    DESCRIPTION VARCHAR2(255) NOT NULL,
    NOMENCLATURE VARCHAR2(255) NOT NULL,
    TYPE VARCHAR2(255) NOT NULL
);
