CREATE SEQUENCE SEQ_ALUNO_OID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ALUNO (OID_ALUNO NUMBER(20) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY (OID_ALUNO));

COMMENT ON COLUMN ALUNO.OID_ALUNO IS 'Identificador da tabela de aluno.';

COMMENT ON TABLE ALUNO IS 'Tabela com as informações dos alunos que pretendem criar uma proposta.';