CREATE OR REPLACE PROCEDURE RETURNS_GUIDANCE_NAME(P_ID_STUDENT IN STUDENTS.ID%TYPE, P_GUIDING_NAME INOUT TEACHERS.NAME%TYPE)
    LANGUAGE PLPGSQL
    AS $$
BEGIN
    SELECT P.NAME
    INTO P_GUIDING_NAME
    FROM PROPOSALS
    INNER JOIN STUDENTS A ON A.ID = PROPOSALS.FK_AUTHOR_UID
    INNER JOIN TEACHERS P ON P.ID = PROPOSALS.FK_LEADER_UID
    WHERE A.ID = P_ID_STUDENT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;
    RAISE EXCEPTION 'STUDENT NOT FOUND';
END;
$$;