drop table "flyway_schema_history";

DROP TABLE STUDENTS CASCADE CONSTRAINTS;
DROP TABLE INTEREST_AREAS CASCADE CONSTRAINTS;
DROP TABLE INTEREST_AREAS_TEACHERS CASCADE CONSTRAINTS;
DROP TABLE EXAMINATIONS CASCADE CONSTRAINTS;
DROP TABLE BOARDS CASCADE CONSTRAINTS;
DROP TABLE BOARDS_EVALUATORS CASCADE CONSTRAINTS;
DROP TABLE ROLES CASCADE CONSTRAINTS;
DROP TABLE PROPOSALS CASCADE CONSTRAINTS;
DROP TABLE TEACHERS CASCADE CONSTRAINTS;
DROP TABLE SEMESTERS CASCADE CONSTRAINTS;
DROP TABLE SUGGESTIONS CASCADE CONSTRAINTS;
DROP TABLE TITLES CASCADE CONSTRAINTS;
DROP TABLE CLASSES CASCADE CONSTRAINTS;
DROP TABLE CLASSES_STUDENTS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQUENCE_STUDENTS;
DROP SEQUENCE SEQUENCE_INTEREST_AREAS;
DROP SEQUENCE SEQUENCE_EXAMINATIONS;
DROP SEQUENCE SEQUENCE_BOARDS;
DROP SEQUENCE SEQUENCE_PROPOSALS;
DROP SEQUENCE SEQUENCE_TEACHERS;
DROP SEQUENCE SEQUENCE_SEMESTERS;
DROP SEQUENCE SEQUENCE_SUGGESTIONS;
DROP SEQUENCE SEQUENCE_TITLES;
DROP SEQUENCE SEQUENCE_CLASSES;
