CREATE OR REPLACE FUNCTION CHECK_STATUS_STUDENT(P_ID_STUDENT IN NUMBER, P_ID_CLASS IN NUMBER)
RETURN VARCHAR2
IS
V_AVERAGE_FINAL NUMBER;
V_STATUS VARCHAR2(20);
BEGIN
    SELECT AVERAGE
    INTO V_AVERAGE_FINAL
    FROM CLASSES_STUDENTS
    WHERE FK_STUDENT_UID = P_ID_STUDENT
    AND FK_CLASS_UID = P_ID_CLASS;

    IF V_AVERAGE_FINAL >= 7
        THEN V_STATUS := 'APPROVED';
    ELSE V_STATUS := 'DISAPPROVED';
    END IF;

RETURN V_STATUS;
END;
/
SHOW ERRORS;

SELECT CHECK_STATUS_STUDENT(6, 2) FROM DUAL;
