CREATE OR REPLACE PROCEDURE CLASS_STUDENT_REPORT
    (P_ID_CLASS IN CLASSES.ID%TYPE)
IS
    CURSOR C_CLASS_STUDENT IS
    SELECT S.NAME AS SEMESTER, C.NAME AS CLASS, S.NAME AS STUDENT, CS.AVERAGE AS AVARAGE 
    FROM STUDENTS S
    INNER JOIN CLASSES_STUDENTS CS ON S.ID = CS.FK_STUDENT_UID
    INNER JOIN CLASSES C ON C.ID = CS.FK_CLASS_UID
    INNER JOIN SEMESTERS S ON S.ID = C.FK_SEMESTER_UID
    WHERE C.ID = P_ID_CLASS;

BEGIN
    FOR RES IN C_CLASS_STUDENT LOOP
        SYS.DBMS_OUTPUT.PUT_LINE(RES.SEMESTER||' - ' ||RES.CLASS||' - ' ||RES.STUDENT||' - ' ||RES.AVARAGE);
    END LOOP;
END;
/
SHOW ERRORS;


BEGIN 
    CLASS_STUDENT_REPORT(1);
END;
