CREATE OR REPLACE PROCEDURE RETURNS_GUIDANCE_NAME
    (P_ID_STUDENT IN STUDENTS.ID%TYPE, P_GUIDING_NAME OUT TEACHERS.NAME%TYPE)
IS
BEGIN
    SELECT P.NAME
    INTO P_GUIDING_NAME
    FROM PROPOSALS
    INNER JOIN STUDENTS A ON A.ID = PROPOSALS.FK_AUTHOR_UID
    INNER JOIN TEACHERS P ON P.ID = PROPOSALS.FK_LEADER_UID
    WHERE A.ID = P_ID_STUDENT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;
    RAISE_APPLICATION_ERROR(-20001, 'STUDENT NOT FOUND SQLCODE= '||SQLCODE||'  SQLERRM= ' ||SQLERRM );
END;
/
SHOW ERRORS;

DECLARE
    V_NAME VARCHAR2(255);
BEGIN
    RETURNS_GUIDANCE_NAME(1,V_NAME);
    DBMS_OUTPUT.PUT_LINE(V_NAME);
END;
