CREATE OR REPLACE PACKAGE pkg_teacher as
FUNCTION COUNT_TEACHER_BY_TITLE(p_nomenclature_title IN VARCHAR2) RETURN NUMBER;
PROCEDURE P_STUDENTS_BY_GUIDANCE(p_teacher_id IN NUMBER, res out sys_refcursor);

END ;

CREATE OR REPLACE PACKAGE BODY PKG_TEACHER as
FUNCTION COUNT_TEACHER_BY_TITLE(p_nomenclature_title IN VARCHAR2) RETURN NUMBER
IS
    V_QUANT_TEACHER NUMBER;
BEGIN
select count(TA.id)
    INTO V_QUANT_TEACHER
    from TEACHERS TA
    inner join TITLES TI on TA.FK_TITLE_UID = TI.ID
    where NOMENCLATURE = p_nomenclature_title;

    RETURN V_QUANT_TEACHER;
END COUNT_TEACHER_BY_TITLE;

PROCEDURE P_STUDENTS_BY_GUIDANCE(p_teacher_id IN NUMBER, res out sys_refcursor)
IS
BEGIN
    open res for
    SELECT T.NAME, count(*)
    FROM PROPOSALS
    INNER JOIN STUDENTS S on S.ID = PROPOSALS.FK_AUTHOR_UID
    INNER JOIN TEACHERS T on T.ID = PROPOSALS.FK_LEADER_UID
    WHERE T.ID = p_teacher_id
    group by T.NAME;

end P_STUDENTS_BY_GUIDANCE;
END PKG_TEACHER;
/
