ALTER TABLE EXAMINATIONS ADD CONSTRAINT FK_EXAMINATIONS_PROPOSAL_PROPOSALS FOREIGN KEY(FK_PROPOSAL_UID) REFERENCES PROPOSALS;
ALTER TABLE EXAMINATIONS ADD CONSTRAINT FK_EXAMINATIONS_TEACHER_TEACHERS FOREIGN KEY(FK_TEACHER_UID) REFERENCES TEACHERS;

ALTER TABLE INTEREST_AREAS_TEACHERS ADD CONSTRAINT FK_INTEREST_AREAS_TEACHERS_INTEREST_AREA_INTEREST_AREAS FOREIGN KEY(FK_INTEREST_AREA_UID) REFERENCES INTEREST_AREAS;
ALTER TABLE INTEREST_AREAS_TEACHERS ADD CONSTRAINT FK_INTEREST_AREAS_TEACHERS_TEACHER_TEACHERS FOREIGN KEY(FK_TEACHER_UID) REFERENCES TEACHERS;

ALTER TABLE BOARDS ADD CONSTRAINT FK_BOARD_CLASS_CLASSES FOREIGN KEY (FK_CLASS_UID) REFERENCES CLASSES;
ALTER TABLE BOARDS ADD CONSTRAINT FK_BOARD_LEADER_TEACHERS FOREIGN KEY (FK_LEADER_UID) REFERENCES TEACHERS;
ALTER TABLE BOARDS ADD CONSTRAINT FK_BOARD_PROPOSAL_PROPOSALS FOREIGN KEY (FK_PROPOSAL_UID) REFERENCES PROPOSALS;

ALTER TABLE BOARDS_EVALUATORS ADD CONSTRAINT FK_BOARDS_EVALUATORS_BOARD_BOARDS FOREIGN KEY(FK_BOARD_UID) REFERENCES BOARDS;
ALTER TABLE BOARDS_EVALUATORS ADD CONSTRAINT FK_BOARDS_EVALUATORS_EVALUATOR_TEACHERS FOREIGN KEY(FK_EVALUATOR_UID) REFERENCES TEACHERS;

ALTER TABLE CLASSES ADD CONSTRAINT FK_CLASSES_TEACHER_TEACHERS FOREIGN KEY(FK_TEACHER_UID) REFERENCES TEACHERS;
ALTER TABLE CLASSES ADD CONSTRAINT FK_CLASSES_SEMESTER_SEMESTERS FOREIGN KEY(FK_SEMESTER_UID) REFERENCES SEMESTERS;

ALTER TABLE CLASSES_STUDENTS ADD CONSTRAINT FK_CLASSES_STUDENTS_STUDENT_STUDENTS FOREIGN KEY(FK_STUDENT_UID) REFERENCES STUDENTS;
ALTER TABLE CLASSES_STUDENTS ADD CONSTRAINT FK_CLASSES_STUDENTS_CLASS_CLASSES FOREIGN KEY(FK_CLASS_UID) REFERENCES CLASSES;

ALTER TABLE TEACHERS ADD CONSTRAINT FK_TEACHERS_TITLE_TITLES FOREIGN KEY (FK_TITLE_UID) REFERENCES TITLES;

ALTER TABLE PROPOSALS ADD CONSTRAINT FK_PROPOSALS_AUTHOR_STUDENTS FOREIGN KEY(FK_AUTHOR_UID) REFERENCES STUDENTS;
ALTER TABLE PROPOSALS ADD CONSTRAINT FK_PROPOSALS_LEADER_TEACHERS FOREIGN KEY(FK_LEADER_UID) REFERENCES TEACHERS;

ALTER TABLE SUGGESTIONS ADD CONSTRAINT FK_SUGGESTIONS_TEACHER_TEACHERS FOREIGN KEY(FK_TEACHER_UID) REFERENCES TEACHERS;

